import { Kysely, PostgresDialect } from 'kysely';
import pg from 'pg';
import type { Generated, ColumnType } from 'kysely';

export interface FeedbackTable {
  /** uuidv7, generated by Postgres 18 */
  id: Generated<string>;
  name: string;
  email: string;
  message: string;
  created_at: ColumnType<Date, never, never>;
}

export interface Database {
  feedback: FeedbackTable;
}

let db: Kysely<Database> | null = null;

/**
 * Lazily-created Kysely instance so the site runs (and tests pass) without
 * a DATABASE_URL — only the feedback POST route touches the database.
 */
export function getDb(): Kysely<Database> {
  if (!db) {
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString) {
      throw new Error('DATABASE_URL is not set');
    }
    // DO managed Postgres serves a cert signed by DO's own CA. Verify
    // against it when DATABASE_CA_CERT is set (App Platform: bind it to
    // ${db.CA_CERT}); otherwise connect encrypted but unverified. The
    // injected DATABASE_URL doesn't reliably say sslmode=require, so the
    // fallback also matches the managed-database hostname.
    const caCert = process.env.DATABASE_CA_CERT;
    const wantsTls = connectionString.includes('sslmode=')
      || connectionString.includes('.ondigitalocean.com');
    db = new Kysely<Database>({
      dialect: new PostgresDialect({
        pool: new pg.Pool({
          connectionString,
          ssl: caCert
            ? { ca: caCert }
            : wantsTls
              ? { rejectUnauthorized: false }
              : undefined,
          max: 5,
          // Fail the request fast when the DB is unreachable — the form
          // falls back to a "email us instead" message
          connectionTimeoutMillis: 5000,
        }),
      }),
    });
  }
  return db;
}
